### ISSUE TITLE
pixhawk 2.4.8 with apm firmware

### ISSUE THREAD

**Issue by kids0cn** [CopterExpress/clover#260]
I try to  communicate to a pixhawk flight controller with apm firmware。 clover on raspi 3+,uart connect to pixhawk,but it cannot work。

is there anyway to make it work?

**Comment by okalachev** [comment]
Hi, the image will work with APM very basically. Change `fcu_conn` to `uart` in `~/catkin_ws/src/clover/clover/launch/clover.launch` (as described [here](https://clover.coex.tech/en/connection.html#uart-connection)) if you use UART connection.

But a lot of features will not work because they require PX4 firmware.
